<?php

return [
    "plugin" => [
        "name" => "Sitemap Pretty",
        "description" =>
            "The Winter Sitemap Pretty plugin allows you to to prettify a sitemap.xml file generated by wn-sitemap-plugin for your website to make it human readable.",
    ],
    "definition" => [
        "not_found" =>
            "No sitemap definition was found. Try creating one first.",
    ],
];